### ISSUE TITLE
Signature mismatch on BUILD

### ISSUE THREAD

**Issue by 0racle** [azawawi/perl6-file-zip#2]
Receiving this error when trying to use the module as described in your example.

```
Cannot call seek(IO::Handle: Int, Int); none of these signatures match:
    (IO::Handle:D $: Int:D $offset, SeekType:D $whence = { ... }, *%_)
  in method _find-eocd-record-offset at .../lib/File/Zip.pm line 130
  in method BUILD at .../lib/File/Zip.pm line 28
  in block <unit> at filezip.p6 line 5
```

**Comment by azawawi** [comment]
Fixed in https://github.com/azawawi/perl6-file-zip/commit/68410a5718fd93ef969806dc424ff64517c0687f. And I am truly sorry for being late on this one.

Thanks for reporting it :+1:
